version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: skyeye-backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:rw
    environment: {}

  frontend:
    build:
      context: ./skyeye-frontend
      dockerfile: Dockerfile.frontend
    container_name: skyeye-frontend
    ports:
      - "3000:3000"
    # Expose the backend to the frontend via service name
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
